# 服务器配置
server:
  port: 28079
  undertow:
    buffer-size: 1024
    direct-buffers: true
    threads:
      io: 16
      worker: 256
  servlet:
    session:
      tracking-modes: cookie


# 项目全局配置
project:
  name: newbee-mall-plus # 项目名称
  #  fileUploadPath: /opt/newbee-mall-plus/upload/  # 上传文件的默认url前缀，根据部署设置自行修改，linux下路径
#  fileUploadPath: D:\\upload\\              # 上传文件的默认url前缀，根据部署设置自行修改，windows下路径
  fileUploadPath: D:\upload\
  orderUnpaidOverTime: 300 # 订单未支付超期时间，单位秒
  serverUrl: http://localhost:28079 # 服务器地址

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes:
  # 匹配链接
  urlPatterns: /admin/*,

# spring配置
spring:
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev



# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml    # mapper映射文件位置

# alipay 需要自行申请支付宝的沙箱账号、申请appID，并依次配置AppID、密钥、公钥，否则无法发起支付宝支付。
alipay:
  app-id: 2021000122605550
  rsa-private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC3/P0Lz+2b6+niIQFcPmzDOs9q9QVhKLeqdJkCl1qzCA+S46HmWHRWzC/4PR1tH1Gh91UmwR+QwNJYz4aFeksAJiwfLqtWK89sYPY4b3xVmn3Ml82iiPWBjIT8VYeAQt1bSEb1E83sXXMm8VlGgoF7Ivi3JPqs2EnrTLBHyLzR6zCrWVvpHYmAZw8NybEtJE6i4dGDQ2PepCEx/mx3hwPRRaqWZP1SPzl6EyK6q3RDACSIyxKR+DYZetjWOzG2poPPealJNY+sfo/HmXaEtqbIzlqj/bPucTJ+UsbGKf8UdMW5pee4bZdzS50JqnAEm1sjqh5ndJ8RnKGqUlC1mqavAgMBAAECggEAXIJf2Wia2CMuXfyqam8Y0LDpSaYZJlkKwDIQHTVs7UfITNsXtHIVTO8tz2srOIreyMlLj0jbTjUljnIJ+WMcAt8uoB8fFxzAFoZKRuYHZiNfzVcmleq3RoQY+acnkl4MXrFgvClRCN+T3qjLcqB76iYTWELHp9C4mg7dM7rC9eiohT4TNM1kL/yiEy18murBSUoKL4KDbD9XGLF6YA9saNQnq98YCEEe/Us05R6OjaA9myQz80EmNHMYfYL/T3IGD71vVhawNeZI2p40JB2UPQeBalHpZE1iI2W1frctpm5qOMvJZxFwGvc7Iu8zgGCWw/V160ykBLonelmEostegQKBgQDrJX4ul2Uy+DSusRq3LRmhMjiZbjJgPSAT2zcoA5bW6ERG0615iVpoKZr/nme5e6U12X/t62KkvQOHhzv3CO4NQU9fn0Zz9hTBGjOMXFY+TjYzX0E8trTctrpl8YMHwpZsmfxoMakDy3H7y06+hrI+JKkFw51vP9G/ZNyq3iEYdwKBgQDITg4zE7BQFrPiEppYF/mNpkWAeeaqo+sSjzUAknC7K//00iPQTDW+frFMkAZrkNuvI9/wkogxqtQSGKZgwhiBeu7w0pibdZn76o/gUeFOesBwd9xSAM2/3Ykk8eOXcHo3wTVCOS5tJmUMn6sibGoVUPLZXUd/vC2b8YxHVrKpiQKBgFKGHfqL92Aj65lDXnTaxxvjXCm8msFbsl5FmN3aJJ3Xdd7FeyQkKC5WK6d6GDzoP9reMh91dHEMRKjTtR/FaoYMXabZZwhbXH1IjL69ySaknDD7RRHhrSeomVIdqDaY++GxSPvoMcC7LY2IlGIZM4TLqOX0+NOKOjpJU4hD3KmRAoGAApLOJ+XW3BCOmxb2GK+mKyW5ut7WEdctS/2/BpTbEeyMy05v21s/TYU/Leajznn7+JITbHnVeh3hv6HFcXTM78zuiPWLtGOcaNooow8qP+Hf2xIPKJaODisAehMJg4aUa2b2EjW93PUjUzgx8K1H56I0nIpQQtneFCTUUo5QmVECgYEAnz4Y6MuRjvwLN3sRlI/d4jYxZl2htNOKtPGDeHKAzAr06Rokz0tswpth4J/1Hjw+6txIUA4qB9CNY9vmoBQPauHgzL9zNVXmSRS9PQwkOYkIbEViEHH1MRHIFRHkThNUoSEa5w/vdtHoPCenRD14l2GrUeoutD79YJaQ2BxEb8w=
  alipay-public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjSKZzZwPttciiPHk8QoIjH1gLHbuX4pcTc4t1fBDi72elVPGpgGnYMIh1heF91uSAcpMs7gI+vAqBhxpuBEKU5EfeiwCpeWpZ4/pL4ISrGmhwudDcZDK+HRrJGcezw1xdP1g0h2Llf5vKENDHvs+hrUR3STuBk6sHtYPVT1OqGYdRbchKrLDHxabRZxwISPG+aZSnomzG7KwFbMbIsKWlzI/Ts4Mqfnf5pVW8mt+CB9Pnge909rFZ2FeWFiJYwvPNAvb2p9kjzrXTsF6OniNrVbHfcdKactNTKZ/3a+l/iPtC9SPcDO0G5JQkbhvaRLfxkEQkFXXGFo924M1IF0PRwIDAQAB
  gateway: https://openapi.alipaydev.com/gateway.do
  charset: UTF-8
  format: json
  #  log-path: /opt/newbee-mall-plus/log
  log-path: D://newbee-mall-plus//log
  signtype: RSA2

payServerUrl: http://s0.z100.vip:23181 #内网穿透地址配置
